name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run tests and create coverage report
      run: sbt clean coverage test assembly coverageReport

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: scoverage-report
        path: target/scala-*/scoverage-report/